website/auth.py
from flask import Blueprint, render_template, request, flash,redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('password')
        
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in Successfuly!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect Password, try again!', category='error')
        else:
            flash('Email does\'t exsist ', category='error')
            
    return render_template("login.html")

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        fullname = request.form.get('fullname')
        password = request.form.get('password')
        passwordc = request.form.get('passwordc')
        gender = request.form.get('gender')
        
        user = User.query.filter_by(email=email).first()
        usernames = User.query.filter_by(username=username).first()
        if user:
             flash("Email Already exists.", category='error')
        elif usernames:
            flash("Email Already exists.", category='error')
        elif len(email) < 4:
            flash("Email must be greater than 4 characters.", category='error')
        elif len(username) < 2:
            flash("username must be greater than 1 characters.",category='error')
        elif len(fullname) < 2:
            flash("Fullname must be greater than 1 characters.",category='error')
        elif password != passwordc:
            flash("Passwords dont\'t match.", category='error')
        elif len(password) < 8 :
             flash("Password must be at least 8 characters",category='error')
        else:
            new_user = User(email=email, username=username,fullname=fullname,password=generate_password_hash(password, method='sha256'), gender=gender,role="user")
            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')
            return redirect(url_for('auth.login'))
        
    return render_template("register.html")

website/templates/add-wallpaper.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Wallpafest - Dashboard</title>

    <!-- Custom fonts for this template-->
    <!-- <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}">
    <!-- <link href="css/sb-admin-2.min.css" rel="stylesheet"> -->

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
                <div class="sidebar-brand-icon rotate-n-15">
                    
                </div>
                <div class="sidebar-brand-text mx-3">Wallpafest</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="/dashboard/{{current_user.username}}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                User
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link" href="/dashboard/{{current_user.username}}/profile">
                    <i class="fa-solid fa-user"></i>
                    <span>Profile</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/logout">
                    <i class="fa-solid fa-right-from-bracket"></i>
                    <span>Logout</span></a>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Wallpaper Management
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="/dashboard/{{current_user.username}}/wallpaper">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Wallpaper</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item active">
                <a class="nav-link" href="/dashboard/{{current_user.username}}/add-wallpaper">
                    <i class="fa-solid fa-plus"></i>
                    <span>Add Wallpaper</span></a>
            </li>
            

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

         
          
        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <br><br>
                     <h1 class="h1 mb-0 text-gray-800" align="center">Upload Wallpaper</h1>
                     <br>
                    <div class="card">
                        <img class="card-img-top" src="holder.js/100x180/" alt="">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                <div class="form-group">
                                  <label for="wallpaperTitle">Wallpaper Title</label>
                                  <input type="text" class="form-control" name="wallpaperTitle" id="wallpaperTitle" aria-describedby="helpId" autocomplete="off" placeholder="Enter your wallpaper title....">
                                </div>
                                <div class="form-group">
                                    <label for="wallpaperSubTitle">Wallpaper Sub-Title</label>
                                    <input type="text" class="form-control" name="wallpaperSubTitle" id="wallpaperSubTitle" aria-describedby="helpId" autocomplete="off" placeholder="Enter your wallpaper sub-title.... (Ex: Genshin Impact, Godzilla, Playstation)">
                                  </div>
                                <div class="form-group">
                                  <label for="">Wallpaper Type</label>
                                  <select class="form-control" name="tipeWallpaper" id="tipeWallpaper" >
                                    <option>Anime</option>
                                    <option>Tech</option>
                                    <option>Beauty</option>
                                    <option>Design</option>
                                    <option>Illustrations</option>
                                    <option>Abstract</option>
                                    <option>Fashion</option>
                                    <option>Arts</option>
                                    <option>Music</option>
                                  </select>
                                </div>
                                <div class="mb-3">
                                    <label for="formFile" class="form-label">Wallpaper File</label>
                                    <input class="form-control" type="file" id="wallpaperFile" name="wallpaperFile" onchange="readURL(this)">
                                </div>
                                <div>
                                    <img src="#" id="imageu" alt="">
                                </div>
                                <br>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                     
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Wallpafest</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <link class="jsbin" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>
    ;
    <script>
        function readURL(input){
            if (input.files && input.files[0]){
                var reader = new FileReader();

                reader.onload = function(e){
                    $('#imageu').attr('src', e.target.result).width(598).height(468);
                };
                reader.readAsDataURL(input.files[0])
            }
        }
    </script>



</body>

</html>

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dark.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/font-icons.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/magnific-popup.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fonts2.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blog.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/colors.php?color15535e') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Domine:wght@400;500;700&family=Roboto:wght@400;500&display=swap">

    <script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
    <script src="{{ url_for('static', filename='js/plugins.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/functions.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js"></script>

    <title>{% block title %}Wallpafest{% endblock %}</title>

</head>
{% block content %}

{% endblock %}
</html>

website/templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <title>{% block title %}Wallpafest{% endblock %}</title>
</head>
<body>

{% with messages = get_flashed_messages(with_categories=true)%}
{% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
        <div class="alert alert-danger alert-dismissable fade show" role="alert">
            {{ message}}
            <button type="button" style="float: right;"  class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% else %}
        <div class="alert alert-success alert-dismissable fade show" role="alert">
            {{ message}}
            <button type="button" style="float: right;"  class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
    {% endfor %}
{% endif %}
{% endwith %}
{% block content %}
    
{% endblock %}
</body>
</html>

website/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Wallpafest - Dashboard</title>

    <!-- Custom fonts for this template-->
    <!-- <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}">
    <!-- <link href="css/sb-admin-2.min.css" rel="stylesheet"> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js" integrity="sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
                <div class="sidebar-brand-icon rotate-n-15">
                    
                </div>
                <div class="sidebar-brand-text mx-3">Wallpafest</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="/dashboard/{{current_user.username}}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                User
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link" href="/dashboard/{{current_user.username}}/profile">
                    <i class="fa-solid fa-user"></i>
                    <span>Profile</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/logout">
                    <i class="fa-solid fa-right-from-bracket"></i>
                    <span>Logout</span></a>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Wallpaper Management
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="/dashboard/{{current_user.username}}/wallpaper">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Wallpaper</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="/dashboard/{{current_user.username}}/add-wallpaper">
                    <i class="fa-solid fa-plus"></i>
                    <span>Add Wallpaper</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

         
          
        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                   
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 ">{{current_user.username}}</span>
                            </a>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
                    </div>

                    <!-- Content Row -->
                    <div class="row">

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <a href="/" style="text-decoration: none;" >
                                <div class="card border-left-primary shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="h5 mb-0 font-weight-bold text-gray-800">PROFILE</div>
                                            </div>
                                            <div class="col-auto">
                                                <i class="fa-solid fa-user fa-2x text-gray-300  "></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <a href="/dashboard/{{current_user.username}}/wallpaper" style="text-decoration: none;" >
                                <div class="card border-left-success shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                                    WALLPAPER</div>
                                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{wallpaper}}</div>
                                            </div>
                                            <div class="col-auto">
                                                <i class="fas fa-fw fa-chart-area fa-2x text-gray-300"></i>
                                            </div>
                                        </div>
                                    </div>
                                 
                                </div>
                            </a>   
                        </div>
                        </div>
                        {% if current_user.role == "admin" %}
                            <div style="width: 300px ;">
                                <center>
                                    <h2>Data User</h2>
                                </center>
                                <canvas id="myChart" width="200" height="200"></canvas>
                            </div>
                        {%endif%}

                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Wallpafest</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <script>
        const ctx = document.getElementById('myChart').getContext('2d');
        const myChart = new Chart(ctx, {
                type: 'pie',
                data : {
                    labels: [
                      'Perempuan',
                      'Laki - Laki',
                    ],
                    datasets: [{
                      label: 'My First Dataset',
                      data: [3, 2],
                      backgroundColor: [
                        'rgb(255, 99, 132)',
                        'rgb(54, 162, 235)',
                        'rgb(255, 205, 86)'
                      ],
                      hoverOffset: 4
                    }]
                  }
                });
    </script>


</body>

</html>

website/templates/login.html
{% extends "base2.html" %}{% block title %} HOME {% endblock %} {% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='real_css/login.css') }}">
<div class="center">
    <h1>Login</h1>
    <form  method="post">
        <div class="txt_field">
            <input type="email" name="email" id="email"  required autocomplete="off">
            <span></span>
            <label for="email">Email</label>
        </div>
        <div class="txt_field">
            <input type="password" name="password" id="password" required autocomplete="off">
            <span></span>
            <label for="password">Password</label>
        </div>
        <input type="submit" value="Login" class="login_button">
        <div class="sign-up">
            Dont have an account? <a href="{{url_for('auth.register')}}">Register</a>
        </div>

    </form>
</div>



{% endblock %}

website/templates/register.html
{% extends "base2.html" %}{% block title %} HOME {% endblock %} {% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='real_css/register.css') }}">
<div class="center">
    <h1>Register</h1>
    <form action="" method="post">
        <div class="txt_field">
            <input type="email" name="email" id="email" required autocomplete="off">
            <span></span>
            <label for="email">Email</label>
        </div>
        <div class="txt_field">
            <input type="text" name="username" id="username" required  autocomplete="off">
            <span></span>
            <label for="username">Username</label>
        </div>
        <div class="txt_field">
            <input type="text" name="fullname" id="fullname" required autocomplete="off">
            <span></span>
            <label for="fullname">Fullname</label>
        </div>
        <div class="txt_field">
          <input type="password" name="password" id="password" required  autocomplete="off">
          <span></span>
          <label for="password">Password</label>
      </div>
      <div class="txt_field">
        <input type="password" name="passwordc" id="passwordc" required autocomplete="off">
        <span></span>
        <label for="passwordc">Password (Confirm) </label>
      </div>
      <div class="form-group mb-4">
        <label for="">Gender</label>
        <select class="form-control" name="gender" id="gender" >
          <option>Laki - Laki</option>
          <option>Perempuan</option>
        </select>
      </div>

        <input type="submit" value="Register" class="login_button mb-3">
        

    </form>
</div>

{% endblock %}